***Numpy***                    

In [1]:
import numpy as np                              #importing numpy

In [2]:
myarr = np.array([2,4,6,8])                      #1  

In [3]:
myarr                    

array([2, 4, 6, 8])

In [4]:
myarr.dtype                                      #to know the type

dtype('int32')

In [5]:
myarr[0]     

2

In [6]:
myarr = np.array([[2,4,6,8]])                     #2

In [7]:
myarr[0,1]

4

In [8]:
myarr.shape                                       #to know the dimesnsion

(1, 4)

In [9]:
myarr[0,1] = 45                                   #assigning new value

In [10]:
myarr

array([[ 2, 45,  6,  8]])

In [11]:
myarr[0]

array([ 2, 45,  6,  8])

***Array Creation***

In [15]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
listarray.shape

(3, 3)

In [18]:
listarray.dtype

dtype('int32')

In [22]:
listarray.size                                       #to know the size

9

***Zeros 0***

In [24]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zeros =np.zeros((2,4))

In [27]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
zeros.shape

(2, 4)

In [29]:
zeros.dtype

dtype('float64')

In [30]:
rng = np.arange(0,15)                                    #arange 

In [31]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
lspace = np.linspace(1,5,7)                         #linspace # 7 linearly space values between 1 to 5  

In [35]:
lspace

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [38]:
emp = np.empty((5,5))                                 #empty array with random values

In [39]:
emp

array([[1.86918699e-306, 1.69121096e-306, 4.45066125e-308,
        1.42419530e-306, 1.60219035e-306],
       [1.42419938e-306, 7.56603881e-307, 8.45603441e-307,
        1.42417221e-306, 1.60219306e-306],
       [6.23059726e-307, 1.06811422e-306, 1.42417221e-306,
        1.37961641e-306, 6.23040033e-307],
       [6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 9.34608432e-307, 8.45593934e-307,
        8.34451079e-308, 3.91792476e-317]])

In [43]:
emp_like =np.empty_like(lspace)               #to inialize empty array with other aaray

In [44]:
emp_like

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [45]:
emp_like.shape

(7,)

In [47]:
ide = np.identity(5)                           #identity matrix

In [48]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
ide.shape

(5, 5)

In [55]:
RS = np.arange(0,99)

In [56]:
RS

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
RS = RS.reshape(3,33)                        #to RESHAPE the array with customized size but it needs to be accurate(n x d =nd)

In [60]:
RS

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [63]:
RS =RS.ravel()                    #to make the array straight

In [64]:
RS

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [65]:
RS.shape

(99,)

In [66]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [67]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [68]:
arr =np.array(x)

In [69]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
arr.sum(axis =0)                         # axis 0 = column

array([12, 15, 18])

In [72]:
arr.sum(axis =1)                         # axis 1 = row

array([ 6, 15, 24])

In [74]:
arr.T                                   #Transpose matrix -axis 0 to 1 ,and axis 1 to 0

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [75]:
for item in arr:
    print(item)

[1 2 3]
[4 5 6]
[7 8 9]


In [76]:
arr.flat                                    # gives iterator 

In [78]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [80]:
arr.ndim                                #number of dimension

2

In [81]:
arr.size

9

In [83]:
arr.nbytes                                    #total bytes consumed

36

In [94]:
one = np.array([1,8,33,22,3,4])                   #index of maximum value

In [95]:
one.argmax()

2

In [101]:
one.argmin()                                       #index of minimum value

0

In [102]:
one.argsort()                                       #sorting by index

array([0, 4, 5, 1, 3, 2], dtype=int64)

In [103]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [105]:
arr.argsort(axis =0)              

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [106]:
arr.argsort(axis =1) 

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [107]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
array =np.array([[1,1,1],[5,2,8],[6,5,4]])

In [110]:
arr+array                                #addition of 2 arrays

array([[ 2,  3,  4],
       [ 9,  7, 14],
       [13, 13, 13]])

In [112]:
arr*array                                   #multiplication of 2 arrays

array([[ 1,  2,  3],
       [20, 10, 48],
       [42, 40, 36]])

In [114]:
np.sqrt(arr)                                #Square Root of an array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [115]:
arr.sum()

45

In [116]:
arr.max()


9

In [117]:
arr.min()

1

In [118]:
np.where(arr>4)                   #finds the index number of desired value

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [120]:
np.count_nonzero(arr)             #counts the amount of non zero element

9

In [127]:
np.nonzero(arr)                     #index of non zero value

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [125]:
arr[1,2] = 0 

In [126]:
np.nonzero(arr)           

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [128]:
import sys

In [131]:
py_ar =[0,4,55,2]

In [132]:
np_ar = np.array(py_ar)

In [138]:
sys.getsizeof(1)*len(py_ar)

112

In [140]:
np_ar.itemsize * np_ar.size

16